spin_manifest_version = 2

[application]
authors = ["The Spin authors"]
name = "rust-outbound-pg-v4-example"
version = "0.1.0"

[[trigger.http]]
route = "/:year"
component = "outbound-pg"

[component.outbound-pg]
environment = { DB_URL = "host=localhost user=postgres dbname=spin_dev" }
source = "../../target/wasm32-wasip1/release/rust_outbound_pg_v4.wasm"
allowed_outbound_hosts = ["postgres://localhost"]
[component.outbound-pg.build]
command = "cargo build --target wasm32-wasip1 --release"
