package spin:sdk;

world imports {
  import wasi:config/store@0.2.0-draft-2024-09-27;
  include wasi:keyvalue/imports@0.2.0-draft2;
  @unstable(feature = wasi-otel)
  include wasi:otel/imports@0.2.0-rc.2;
}