#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
authors = ["The Spin authors"]
description = "An application that returns hello."
name = "hello-world"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"
executor = { type = "wasip3-unstable" }

[component.hello]
source = "../../target/wasm32-wasip2/release/wasip3_hello_world.wasm"
description = "A component that returns hello."
[component.hello.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*.rs", "Cargo.toml"]